### ISSUE TITLE
Visual indicator for who has to play the next card

### ISSUE THREAD

**Issue by thielepaul** [DanielAndreSchneider/Schafkopf#14]

**Comment by DanielAndreSchneider** [comment]
Why do we have a list of connectionIDs for each player and not only one connectionID?

**Comment by thielepaul** [comment]
> Why do we have a list of connectionIDs for each player and not only one connectionID?

My idea was that it might happen, that one player is connected to the same game in two tabs. 
On second thought it should suffice to save the last connectionId and only send updates there.
